name: iden
description: IDEN
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get: ^4.6.5
  flutter_svg: ^2.0.7
  flutter_native_splash: ^2.3.1
  http: ^1.1.0
  permission_handler: ^10.4.3
  contacts_service: ^0.6.3
  badges: ^3.1.1
  flutter_secure_storage: ^8.0.0
  url_launcher:
  sms_autofill: ^2.3.0
  image_picker: ^1.0.1
  flip_card: ^0.7.0
  awesome_dialog: ^3.1.0
  pull_to_refresh:
  modal_bottom_sheet: 3.0.0-pre
  shimmer: ^3.0.0
  lottie: ^2.5.0
  path_provider: ^2.0.15
  just_the_tooltip: ^0.0.12
  appinio_swiper: ^2.0.2
  image: ^4.0.17
  palette_generator: ^0.3.3+2
#  flutter_sms: ^2.3.3
  shared_preferences: ^2.2.0
  fluttertoast: ^8.2.2
  webview_flutter:
  image_editor:
  cached_network_image: ^3.2.3
  system_settings: ^2.1.0
  animated_flip_counter: ^0.2.6
  flutter_inappwebview: ^5.7.2+3
  image_gallery_saver: ^2.0.3
  sticky_headers: ^0.3.0+2
  flutter_slidable: ^3.0.0
  screenshot: ^2.1.0
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  web3dart: ^2.7.0
  ntcdcrypto: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animation/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Thin.otf
          weight: 100
        - asset: assets/font/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/font/Pretendard-Light.otf
          weight: 300
        - asset: assets/font/Pretendard-Regular.otf
          weight: 400
        - asset: assets/font/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/font/Pretendard-Bold.otf
          weight: 700
        - asset: assets/font/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/font/Pretendard-Black.otf
          weight: 900
    - family: Clash
      fonts:
        - asset: assets/font/ClashDisplay-Semibold.otf
          weight: 600
        - asset: assets/font/ClashDisplay-Bold.otf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_icon.png'
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app_icon.png

  android_12:
    image: assets/images/app_icon.png
    fullscreen: true

  android_gravity: center
  ios_content_mode: center
  fullscreen: true
